services:
    Webfactory\VisibilityFilterBundle\Filter\FilterStrategy:
        alias: 'Webfactory\VisibilityFilterBundle\Filter\HatBestimmtenWertImSichtbarkeitsfeld'

    Webfactory\VisibilityFilterBundle\Filter\HatBestimmtenWertImSichtbarkeitsfeld:
        arguments:
            - 'y'

    Webfactory\VisibilityFilterBundle\Filter\VisibilityColumnRetriever:
        arguments:
            - '@Doctrine\Common\Annotations\Reader'

    Webfactory\VisibilityFilterBundle\DependencyInjection\DependencyInjectorForDoctrineFilter:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Webfactory\VisibilityFilterBundle\Filter\VisibilityColumnRetriever'
            - '@Webfactory\VisibilityFilterBundle\Filter\FilterStrategy'
        tags:
            - { name: kernel.event_subscriber }
