on: [push]
name: Tests
env:
  APP_ENV: test
  PHP_VERSION: 8.1
  TEMP: ${{ github.workspace }}/tmp

jobs:
  PHPUnit:
    name: PHPUnit (PHP 8.1)
    runs-on: ubuntu-22.04
    steps:
      -   uses: actions/checkout@v4
      -   name: Configure Composer
          run: |
            mkdir -p ~/.composer/cache
      -   run: mkdir --mode=777 -p $GITHUB_WORKSPACE/{tmp,logs}
      -   name: Konfiguriere PHP-Version und -Einstellungen im Worker-Node
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ env.PHP_VERSION }}
            coverage: none
            tools: composer:v2
            ini-values: variables_order=EGPCS
            # Falls spezielle Extensions installiert werden müssen:
            # extensions: intl, mbstring
      -   name: Cache Composer Dependencies
          uses: actions/cache@v4
          with:
            path: vendor/
            key: composer-${{ env.PHP_VERSION }}-${{ hashFiles('composer.*') }}
            restore-keys: |
              composer-${{ env.PHP_VERSION }}-${{ github.ref }}
              composer-${{ env.PHP_VERSION }}-
      -   run: |
            composer install --no-interaction --no-scripts --no-progress --no-suggest
            composer show
      -   run: vendor/bin/phpunit -vvv
